### ISSUE TITLE
ImportError in arcli

### ISSUE THREAD

**Issue by mellonwand** [autotest/arc#1]
arcli --help returned  this error:
import arc.shared.frontend
ImportError: No modules named shared.frontend

A few days ago's version of arcli is right.

**Comment by clebergnu** [comment]
This may actually be caused by environment changes (your `PYTHONPATH`). But, since this is a recurring problem, I've just pushed a patch to the `master` branch which should fix this.

Can you please update your copy and try again?

Thanks.

**Comment by mellonwand** [comment]
I don't know why it didn't work yesterday. The python2.x/site-packages/ should be set in PYTHONPATH.

Now it works fine.

Thank you.

**Comment by clebergnu** [comment]
You're welcome.
