### ISSUE TITLE
arcli job --from-test-number RFE

### ISSUE THREAD

**Issue by clebergnu** [autotest/arc#4]
This is just a couple of suggestions that I thought that could improve usage of the newly added (and great) `--from-test-number` option:
- could look up and set test type (it's easy to send client jobs erroneously as server jobs and vice verse - the default)
- could set the job name by default, using the test name

This would allow a user experience such as:

```
$ arcli job -a -m testhost -T 57
```

Which is great IMHO.

**Comment by clebergnu** [comment]
Just expanding the usability here, if user already has something like:

```
[job]
...
machines = autotest-client.example.com
```

Then the command could be as simple as:

```
arcli job -a -T 57
```

Even sweeter IMHO!

**Comment by ruda** [comment]
I'm closing, it's merged.
