### ISSUE TITLE
Short license header on every file

### ISSUE THREAD

**Issue by clebergnu** [autotest/arc#5]
The Fedora review process suggested that we add a short license header to every file. Something as simple as:

```
Copyright (C) 2014 John Doe <jdoe@redhat.com>
License: GPLv2 (see LICENSE for details)
```

Also, add license indication on `README.MD`.

**Comment by ruda** [comment]
What about to use something more verbose and informative, like this:

<pre>
# This program is free software; you can redistribute it and/or modify          
# it under the terms of the GNU General Public License as published by          
# the Free Software Foundation; either version 2 of the License, or             
# (at your option) any later version.                                           
#                                                                               
# This program is distributed in the hope that it will be useful,               
# but WITHOUT ANY WARRANTY; without even the implied warranty of                
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#                                                                               
# See LICENSE for more details.
#
# Copyright (c) 2013-2014 Red Hat
# Author: Cleber &lt;cleber@redhat...&gt;
</pre>

**Comment by lmr** [comment]
That's not bad indeed.

**Comment by lmr** [comment]
Maybe we can write a script to jam this in every file for all our projects.

**Comment by ruda** [comment]
That's right @lmr! I will use some script to insert on each Python file of the project. Next step.

**Comment by ruda** [comment]
Here's the script I'm using to insert the license notice. Some hand mades fixes was necessary too.

<pre>
#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
def usage():
    print 'Usage:', sys.argv[0], '&lt;license> &lt;files...>'
    sys.exit(0)
def insert_comment(text, file_py):
    with open(file_py) as py:
        content = py.read()
        new_content = text + '\n' + content
    with open(file_py, 'w') as py:
        py.write(new_content)
if __name__ == '__main__':
    if not sys.argv[1:]:
        usage()
    license_notice = sys.argv[1]
    files = sys.argv[2:]
    with open(license_notice) as license:
        content = license.read()
    for f in files:
        insert_comment(content, f)
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
</pre>

**Comment by lmr** [comment]
Sure, I imagined some manual tweak would be necessary. Now after autotest 0.16 (I'm writing the release notes now), we shall use that in the entire code base of autotest, virt-test and test providers.

**Comment by clebergnu** [comment]
Since the pull request has been merged, I'm closing this issue. Let's maybe open another one on autotest / virt-test to track the license naming on those modules.
