### ISSUE TITLE
Add option -Q USERNAME, --username=USERNAME

### ISSUE THREAD

**Issue by ruda** [autotest/arc#6]
Implement the option `-Q USERNAME`, `--username=USERNAME` for commands, in order to allow to specify an username to login or use when interacting with Autotest Server.

The default username, when this option is missing, is the proper user name (login) that the command arcli is running, otherwise It's possible to pass the environment variable `ARC_USER` or use the key name `username` inside the section `server` to overwrite this condition.

**Comment by clebergnu** [comment]
Cool! This is something that is really needed!

**Comment by clebergnu** [comment]
Merged!
